# Example for running a local registry in your cluster to use for caching purposes
#
# Note: this will not be visible to the underlying container runtime, so you won't
# be able to run images in the cluster from this registry, but you can use it
# as a cache for a multi-node cluster to speed up builds so every builder has access
# to the same cached content

# TODO explore a variant of this for Host networking, binding to localhost on port 5000
#      and see if that's viable for a local dev registry pattern

apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: docker.io/registry
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: ClusterIP
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 5000
