#@ load("@ytt:data", "data")

apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
- image: registry.default.svc.cluster.local:5000/dkalinin/k8s-simple-app
  path: .
  kubectlBuildKit: {}

#@ if/end data.values.push_images_repo:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
destinations:
- image: registry.default.svc.cluster.local:5000/dkalinin/k8s-simple-app
  newImage: #@ data.values.push_images_repo
